T10782: openssl CI on Windows OS
trassir/conan-center-index pull request #248
Opened 2020-09-29 13:23 UTC by artem-kamyshev

2020-10-13 09:22 UTC, Artalus requested changes

2020-10-13 09:22 UTC, Artalus commented on .github/workflows/openssl.yml
> +            archs: 'x86_64'
Я упустил это для предыдущих рецептов - в архитектурах нам нужна `x86`, по идее, поскольку трассир на винде мы собираем 32битный

2020-10-14 08:55 UTC, Artalus approved these changes

2020-10-14 10:45 UTC, worldemar approved these changes

2020-10-14 15:59 UTC, merged