Ffmpeg 3.3.1 win32 CI, vc 2019
trassir/conan-center-index pull request #262
Opened 2021-01-22 13:51 UTC by artem-kamyshev

2021-02-02 09:39 UTC, worldemar approved these changes

2021-02-02 09:53 UTC, Artalus requested changes

2021-02-02 09:53 UTC, Artalus commented on .github/workflows/ffmpeg-win32-3.3.1.yml
> +        run: git config --global core.autocrlf input
`false` для соответствия остальным ямлам

2021-02-02 09:53 UTC, Artalus commented on recipes/intel_media_sdk/2018R2_1/conanfile.py
> +            self.copy(pattern="*.dll", dst="bin", src=os.path.join(install_dir, 'bin', 'Win32'),
не `x64`?

2021-02-02 09:53 UTC, Artalus commented on recipes/intel_media_sdk/2018R2_1/README.md
> +[![Download](https://api.bintray.com/packages/bincrafters/public-conan/intel_media_sdk%3Abincrafters/images/download.svg) ](https://bintray.com/bincrafters/public-conan/intel_media_sdk%3Abincrafters/
шаблонный файл с неактуальными данными, лишнее

2021-02-02 09:53 UTC, Artalus commented on .github/workflows/ffmpeg-win32-3.3.1.yml
> +      - 'recipes/intel_media_sdk/2018R2_1/**'
должно идти отдельным ямлом

2021-02-04 09:55 UTC, Artalus approved these changes

2021-02-04 09:56 UTC, merged