T11925: allow upload for staging packages
trassir/conan-center-index pull request #270
Opened 2021-02-04 15:13 UTC by worldemar

Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-02-04 17:21 UTC, worldemar commented
see #270

2021-02-08 15:15 UTC, artem-kamyshev requested changes

2021-02-08 15:15 UTC, artem-kamyshev commented on .github/workflows/all.yml
> +            vs_runtimes: 'MD,MT'
Для `debug` рантайм тоже нужен отладочный: `MDd, MDt`.

2021-02-08 18:14 UTC, artem-kamyshev approved these changes

2021-02-09 13:35 UTC, Artalus requested changes

2021-02-16 10:53 UTC, Artalus requested changes

2021-02-16 10:53 UTC, Artalus commented on .github/workflows/prospector.yml
> +      - '.github/workflows/prospector.yml'
наверное, recipes и trassir лишнее?

2021-02-16 10:53 UTC, Artalus commented on .github/workflows/prospector.yml
> +        os: [ubuntu-latest, windows-latest, macos-latest]
есть ли смысл гонять проспектор отдельно на разных платформах?

2021-02-16 10:53 UTC, Artalus commented on builder/conan_tools.py
> +            raise RuntimeError('File {filename} does not exist')
.format потерялся

2021-02-16 12:36 UTC, Artalus approved these changes

2021-02-16 12:41 UTC, merged