T12424: update icu and libiconv for webkit
trassir/conan-center-index pull request #315
Opened 2021-07-19 10:52 UTC by reymondzzzz

Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-07-19 12:12 UTC, worldemar requested changes

2021-07-19 12:12 UTC, worldemar commented on recipes/libiconv/1.16.dssl1/conanfile.py
> +        #
при чём тут айфон? Или это не ты сам написал? Тогда где ссылка на источник? Прочему правки вместе с добавлением файла в одном коммите?

2021-07-19 12:24 UTC, reymondzzzz commented on recipes/libiconv/1.16.dssl1/conanfile.py
> +        #
поправил

2021-07-19 16:05 UTC, worldemar approved these changes

2021-07-20 11:57 UTC, Artalus approved these changes

2021-07-20 11:57 UTC, Artalus commented on recipes/icu/all/conanfile.py
> +        if tools.os_info.is_windows and "CONAN_BASH_PATH" not in os.environ:
если здесь ты убирал проверку на msys2, то добавь комент

2021-07-21 12:40 UTC, merged