T12424: !!!FINAL COMMIT!!! fixes for webkit
trassir/conan-center-index pull request #320
Opened 2021-07-19 10:56 UTC by reymondzzzz

Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-07-19 16:11 UTC, worldemar requested changes
Дождаться проверок и переименовать.

2021-07-23 09:57 UTC, worldemar approved these changes

2021-07-23 10:09 UTC, Artalus requested changes

2021-07-23 10:09 UTC, Artalus commented on recipes/qtwebkit/5.212.0-alpha4.dssl1/conanfile.py
> +        requires.append("libxcomposite/0.4.5")
это должно быть в `requirements(self)`

2021-07-23 10:09 UTC, Artalus commented on trassir/lnvr-gcc8/conanfile.txt
> +freetype:with_bzip2=True
здесь ниже разделить `shared` и остальные флаги, чтобы не возникало ощущения что `opencv:shared=False`

2021-07-23 10:46 UTC, Artalus requested changes

2021-07-23 10:46 UTC, Artalus commented on recipes/qtwebkit/5.212.0-alpha4.dssl1/conanfile.py
> +            requires.append("libxcomposite/0.4.5")
`self.requires`

2021-07-23 11:38 UTC, Artalus approved these changes

2021-07-23 13:20 UTC, merged