T16399: add components in icu recipe
trassir/conan-center-index pull request #335
Opened 2021-07-26 16:49 UTC by reymondzzzz

Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-07-28 08:34 UTC, worldemar approved these changes

2021-08-23 09:15 UTC, Artalus requested changes

2021-08-23 09:15 UTC, Artalus commented on recipes/icu/config.yml
> +  "64.2.dssl1_components":
просто `dssl1` здесь и далее

2021-08-23 10:03 UTC, Artalus approved these changes

2021-08-23 10:29 UTC, merged