T16399: update boost recipe to conan-center-index(master) with compon…
trassir/conan-center-index pull request #336
Opened 2021-07-26 19:21 UTC by reymondzzzz

…ents

Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-07-28 09:39 UTC, worldemar requested changes

2021-07-28 09:39 UTC, worldemar commented on recipes/boost/all/patches/DSSL_JIRA_GRAB3032.patch
> -     DWORD last_error = ::GetLastError();
я думаю этот файлик таки надо оставить

2021-07-28 10:11 UTC, worldemar approved these changes

2021-08-23 09:16 UTC, Artalus requested changes

2021-08-23 09:16 UTC, Artalus commented on recipes/boost/config.yml
> +    1.69.0.dssl1_components:
просто `dssl1` здесь и ниже

2021-08-23 10:03 UTC, Artalus approved these changes

2021-08-23 13:10 UTC, merged