T18806: Build SignalR library x64
trassir/conan-center-index pull request #375
Opened 2022-01-13 14:19 UTC by azamatbakhov

Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-01-19 08:46 UTC, Artalus requested changes

2022-01-19 08:46 UTC, Artalus commented on recipes/signalr-qt/all/conanfile.py
> +            self.output.info("Failed to set the taget to dll: [%s]" % qmake_pro_file)
опечатка, `taRget`

2022-01-19 08:46 UTC, Artalus commented on recipes/signalr-qt/all/conanfile.py
> +        file_content = file_content.replace("staticlib", "dll")
это бы через применение патча делать, а не вслепую заменять все staticlib в файле

2022-01-19 08:46 UTC, Artalus commented on recipes/signalr-qt/all/conanfile.py
> +                signalr_pro_file = os.path.join(self._source_subfolder, "SignalRLibraries/SignalRClient/SignalRClient.pro")
поддерживаю идею с добавлением коммента

2022-01-19 14:18 UTC, Artalus requested changes

2022-01-19 14:18 UTC, Artalus commented on recipes/signalr-qt/all/conanfile.py
> +        # wich are statically linked to SignalRClient.dll.
`wHich`

2022-01-20 11:12 UTC, Artalus approved these changes

2022-01-21 07:03 UTC, worldemar approved these changes

2022-01-21 07:04 UTC, merged