D12679
trassir/conan-center-index pull request #413
Opened 2022-04-28 07:46 UTC by sklyushin

T12775: Add pgdump/9.2 package

2022-04-28 10:18 UTC, worldemar approved these changes

2022-05-17 09:40 UTC, Artalus requested changes
- ~если эта штука собирается на гитхабе, то имя ей никак не `@trassir/sdk120`, а просто `pgdump/9.3.4`~ ошибся, всё норм

- всё это великое множество одинаковых коммитов нужно будет схлопнуть в 1, перед тем как мержить PR

2022-05-18 10:36 UTC, Artalus approved these changes

2022-06-22 09:45 UTC, Artalus approved these changes

2022-07-06 15:05 UTC, merged