T21109: refactoring jenkins file from declarative pipeline to scripted pipeline
trassir/conan-center-index pull request #438
Opened 2022-09-09 13:16 UTC by Evslav

2022-09-12 14:56 UTC, Artalus requested changes

2022-09-12 14:56 UTC, Artalus commented on .jenkins/Jenkinsfile
> +        withConditionalCheck(platform, buildType) {
эээто конечно интересная идея :thinking: 
Но я как-то с годами охладел к концепту злоупотребления `withX{}`. Возможно `if (! platformShouldBeChecked(platform, buildType)) { markSkipped(); return }` будет читаемее

2022-09-12 14:56 UTC, Artalus commented on .jenkins/Jenkinsfile
> +    "GITHUB_REPOSITORY=Conan/conan-center-index.git",
стоит пихнуть сюда пару комментариев, что гитхаб тут по историческим причинам потому что нам лень править билд.пу

2022-09-12 14:56 UTC, Artalus commented on .jenkins/Jenkinsfile
> +                    docker.withRegistry('https://registry.hub.docker.com/') {
зачем здесь дефолтный регистри? оО

2022-09-12 14:56 UTC, Artalus commented on .jenkins/Jenkinsfile
> +    sh("rm -rf ./* ./.[!.]*")
сюда бы коммент о том, что это такая хитроумная очистка мусора оставшегося от прошлой сборки под рутом

и объяснение, почему нельзя сделать просто `sudo rm -rf somedir` + `dir(somedir)` :slightly_smiling_face:

2022-09-12 14:56 UTC, Artalus commented on .jenkins/Jenkinsfile
> +        checkout scm
он что, может вот так за здорово живёшь работать без указания параметров?

2022-09-12 16:01 UTC, Evslav commented on .jenkins/Jenkinsfile
> +                    docker.withRegistry('https://registry.hub.docker.com/') {
потому что https://registry.hub.docker.com/r/trassiross/conan-gcc8 и насколько я помню в нашем локальном режестри его никто не публиковал

2022-09-13 13:31 UTC, vgerasimov11 approved these changes

2022-09-13 16:05 UTC, worldemar requested changes

2022-09-13 16:05 UTC, worldemar commented on .jenkins/Jenkinsfile
> +        withConditionalCheck(platform, buildType) {
`withConditionalCheck` - это **очень общее название для враппера**.
Я его прочитал как "какой-то generic if" и подумал, что он проверяет, что `platform == buildType`.
Если всё что надо - это выполнить или не выполнить скоуп - то для этого придуман оператор `if`

А ещё туда передаётся platform и buildType, а проверяется там вообще другое.
В частности там матчится `giteaPRFilesMatch("^builder/*")`.
Из названия и интерфейса вообще не ясно, что это за штука и почему она требует передачу замыкания внутрь.

Я голосую за `if (! runNeeded(platform, buildType)) { markSkipped(); return }`
т.е. за if и за смену названия на такое, которое отражает смысл функции: вернуть true/false если данный pipeline надо запускать/пропускать.

2022-09-13 17:15 UTC, worldemar approved these changes

2022-09-14 08:30 UTC, Artalus approved these changes

2022-09-14 14:45 UTC, merged